# Generated by Django 5.0.4 on 2024-05-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_text', models.CharField(max_length=50, verbose_name='HomeBgInfo text static')),
                ('dinamic_text1', models.CharField(max_length=50, verbose_name='HomeBgInfo text1 dinamic')),
                ('dinamic_text2', models.CharField(max_length=50, verbose_name='HomeBgInfo text2 dinamic')),
                ('dinamic_text3', models.CharField(max_length=50, verbose_name='HomeBgInfo text3 dinamic')),
                ('about', models.TextField(verbose_name='HomeBgInfo')),
                ('button_name', models.CharField(max_length=20, verbose_name='HomeBgInfo button name')),
            ],
        ),
    ]
