# Generated by Django 5.0.4 on 2024-05-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(verbose_name='About text1')),
                ('text2', models.TextField(verbose_name='About text2')),
                ('text3', models.TextField(verbose_name='About text3')),
                ('text4', models.CharField(max_length=50, verbose_name='About text4')),
            ],
        ),
    ]
