# Generated by Django 5.0.4 on 2024-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Project image')),
                ('name1', models.CharField(max_length=50, verbose_name='Project name1')),
                ('name2', models.CharField(max_length=50, verbose_name='Project name2')),
                ('text1', models.TextField(verbose_name='Project text1')),
                ('text2', models.TextField(verbose_name='Project text2')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
