# Generated by Django 5.0.4 on 2024-05-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='person', verbose_name='Person image')),
                ('name', models.CharField(max_length=50, verbose_name='Person name')),
                ('position', models.CharField(max_length=60, verbose_name='Person position')),
                ('fb', models.TextField(blank=True, verbose_name='Person fb')),
                ('insta', models.TextField(blank=True, verbose_name='Person insta')),
            ],
        ),
    ]