# Generated by Django 5.0.4 on 2024-12-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone2',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='GalleryRio name')),
                ('img', models.ImageField(upload_to='gallery', verbose_name='Gallery image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rio_proj', to='main.project')),
            ],
        ),
        migrations.DeleteModel(
            name='GalleryRio',
        ),
    ]
